name: Update Data
on:
  push:
    branches: [ update-data ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm install
    - name: Run Script
      run: node update_data.js
    - name: Add changes to commit
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        number=$(find data -type f | wc -l)
        let number-=2
        echo "Anzahl der Nodes: $number"
        git add data/*
        git commit -m "🗃 - Auto-Datenupdate $number "
    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Auto-commit changes
        branch: main
        commit-message: Auto-commit changes
