name: Update Data HU
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm install
    - name: Run Script
      working-directory: ./hu
      run: node update_data.js
    - name: Add changes to commit
      run: |
        git config --global user.email "np-reply@example.com"
        git config --global user.name "GH Action"
        number=$(find hu/data -type f | wc -l)
        let number-=2
        echo "Anzahl der Nodes: $number"
        git add hu/data/*
        git commit -m "🗃 - Auto-Update HU $number Nodes"
    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Auto-commit Data Update HU
        commit-message: Overpass query from Openstreetmap
        branch: update-data
        delete-branch: true
